### PR TITLE
wip: proposal: refactor!: adopt result-based error handling instead of relying to exceptions

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind design

**Any specific area of the project related to this PR?**

/area plugin-sdk

**What this PR does / why we need it**:

The current error-handling measure adopted by the SDK consists in the SDK throwing exceptions in wrong paths, and then let the user interrupt in the middle of the plugin SDK business logic, or catching them manually for controlling the execution flow. The SDK catch all unhandled exceptions automatically for safety. This comes with the following limitations:
- Depending on the compiler, exceptions and their handling may be impactful for performance
- Exceptions in C++ are implicit and make it very unpredictable where and when an SDK utility may fail
- There is no code suggestion or enforcement that could invite developers to catch errors
- There is no way of distinguishing a runtime unsafe situation (e.g. non-terminating unexpected execution) from simple errors

As the C++ community is moving towards the proposal of adding [`std::expected`](https://en.cppreference.com/w/cpp/utility/expected) as an extra error reporting method, I'd propose doing the same here. It is pretty much like [`std::result`](https://doc.rust-lang.org/std/result/) of Rust. I agree with the principles of [this articole](https://www.foonathan.net/2017/12/exceptions-vs-expected/), and I'd propose adopting both exceptions and `std::expected` each for their purposes: the former for really unexpected situations, and the latter for general error handiling in regular code paths.

`std::expected` is expected to come in C++23 AFAIK, but I found this cool header-only implementation (https://github.com/TartanLlama/expected) that is friendly to older standards (C++11 being the lower bound from my understanding). Since this is still non-standard, the idea would be to mask it under our own facade types `falcosecurity::res<T>` and `falcosecurity::err`, and adopt them in the SDK utilities wherever applicable. I'm gonna list the benefits of this approach here below:
- Defining our custom result types also gives us extra control on the size of the result objects themselves, which now counts more given that function results will (hopefully) be stack allocations. The proposed implementation of `falcosecurity::err` has the same size as a pointer, and `falcosecurity::res<T>` has a size slightly larger than the simple type `T`, not bad.
- Errors are now explicit and are marked with `[[nodiscard]]`, which means that compilers will provide a contextual warning in case the value is not properly handled
- Code is expected to be more performant and predictable than before
- Since exceptions always represent unsafe and unexpected situations, they now also translate to a static assertion when built in debug mode

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

cc @falcosecurity/plugin-sdk-cpp-maintainers
cc @Andreagit97, with whom I discussed privately about the issue

**Does this PR introduce a user-facing change?**:

```release-note
refactor!: adopt result-based error handling instead of relying to exceptions
```

### CODE REVIEW

**Comment by leogr** [comment]
cc @jasondellaluce 

/remove-lifecycle stale

**Comment by FedeDP** [comment]
Is this something being actively worked on?

**Comment by leogr** [comment]
Hey @jasondellaluce 

do you still plan to work on this? :thinking:

**Pull request closed without merging**
